- name: Play - deploy static website
  hosts: ec2
  become: true
  gather_facts: false
  vars:
    webserver: nginx
    webserver_root_dir: /var/www/html
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "The value of webserver is {{ webserver }}"
    - name: Webserver is installed
      ansible.builtin.package:
        name: "{{ webserver }}"
        state: present
    - name: Webserver is running
      ansible.builtin.service:
        name: "{{ webserver }}"
        state: started
    - name: Webserver root directory exists
      ansible.builtin.file:
        path: "{{ webserver_root_dir }}"
        state: directory
        mode: u=rwX,g=srX,o=rX
    - name: Static website is deployed
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/abdennour/example-static-website/ansible-course/index.html
        dest: "{{ webserver_root_dir }}"
