- name: Play - generate SPECS report
  hosts: all
  tasks:
  - name: Report is generated
    ansible.builtin.template:
      src: ./32-file.conf
      dest: /tmp/specs.conf
      mode: u=rwX,g=srX,o=rX
